# Generated by Django 5.1.6 on 2025-05-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='allowance',
            new_name='Allowance',
        ),
    ]
