# Generated by Django 5.1.6 on 2025-05-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
